#!/usr/bin/env python3
# Copyright 2026 Daniel Tyukov
# SPDX-License-Identifier: Apache-2.0
"""Place and route both variants through LibreLane on the IHP SG13G2 PDK.

What this adds over `make pdk`, which stops after synthesis:

  - post-route die area per variant, so the synthesis-to-route inflation can be
    measured. The pipelined variant has four times the registers of the folded
    one and far more wiring, so the two do not inflate by the same factor, and a
    synthesis-only comparison flatters the pipelined design.
  - DRC and LVS signoff, from magic, KLayout and netgen.
  - a GDS, which scripts/render_gds.py turns into a layout figure.

Timing is deliberately not taken from here. See pnr/README.md.
"""

import argparse
import json
import os
import pathlib
import re
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
RTL = ROOT / "rtl"
PNR = ROOT / "pnr"
OUT = ROOT / "docs" / "pnr"
BUILD = ROOT / "build" / "pnr"

SOURCES = [
    "cordic_stage.sv", "cordic_core_pipe.sv", "cordic_core_iter.sv",
    "cordic_pre.sv", "cordic_post.sv", "cordic_unit.sv", "cordic_fifo.sv",
    "cordic_obi_regs.sv", "cordic_accel.sv",
]

# Clock periods come from what `make pdk` actually measured at the slow corner,
# rounded up. Asking PnR to close on a period synthesis cannot reach wastes an
# hour and produces a violated run.
CONFIGS = [
    dict(name="pipe_q3_29_n28", variant=0, data_width=32, frac_bits=29,
         num_stages=28, period_ns=18.0, util=35, top="cordic_pnr_pipe"),
    dict(name="iter_q3_29_n28", variant=1, data_width=32, frac_bits=29,
         num_stages=28, period_ns=22.0, util=40, top="cordic_pnr_iter"),
]
DEFAULTS = dict(guard_int=2, guard_frac=4, in_depth=4, out_depth=4)

# The metrics worth extracting from LibreLane's flat metrics dict.
METRICS = [
    "design__instance__count",
    "design__instance__area",
    "design__die__area",
    "design__core__area",
    "design__instance__utilization",
    "timing__setup__ws",
    "timing__hold__ws",
    "timing__setup__tns",
    "route__drc_errors",
    "route__wirelength",
    "magic__drc_error__count",
    "klayout__drc_error__count",
    "design__lvs_error__count",
    "antenna__violating__nets",
    "power__total",
]


WRAPPER_TEMPLATE = """// Copyright 2026 Daniel Tyukov
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by scripts/run_pnr.py for the {name} configuration.
//
// LibreLane drives synthesis without exposing Yosys's chparam, so the parameters
// are fixed by wrapping cordic_accel rather than by overriding them. A wrapper
// keeps the RTL free of flow-specific defines, and since it only passes ports
// through it adds nothing to place and route.

module {top} (
  input  logic clk_i,
  input  logic rst_ni,

  input  logic                 obi_req_i,
  output logic                 obi_gnt_o,
  input  logic [31:0]          obi_addr_i,
  input  logic                 obi_we_i,
  input  logic [3:0]           obi_be_i,
  input  logic [31:0]          obi_wdata_i,
  input  logic [2:0]           obi_aid_i,
  output logic                 obi_rvalid_o,
  input  logic                 obi_rready_i,
  output logic [31:0]          obi_rdata_o,
  output logic [2:0]           obi_rid_o,
  output logic                 obi_err_o,

  output logic                 irq_o,

  input  logic                 str_in_valid_i,
  output logic                 str_in_ready_o,
  input  logic [4:0]           str_in_func_i,
  input  logic [7:0]           str_in_tag_i,
  input  logic signed [{dw_m1}:0] str_in_x_i,
  input  logic signed [{dw_m1}:0] str_in_y_i,
  input  logic signed [{dw_m1}:0] str_in_z_i,

  output logic                 str_out_valid_o,
  input  logic                 str_out_ready_i,
  output logic signed [{dw_m1}:0] str_out_x_o,
  output logic signed [{dw_m1}:0] str_out_y_o,
  output logic signed [{dw_m1}:0] str_out_z_o,
  output logic [3:0]           str_out_flags_o,
  output logic [4:0]           str_out_func_o,
  output logic [7:0]           str_out_tag_o
);

  // The observation ports exist for the testbench and the documentation figures.
  // A real integration leaves them unconnected, so they are terminated here and
  // marked as a false path in pnr/cordic.sdc.
  logic [{ns}:0]        unused_stage_valid;
  logic                 unused_iter_valid;
  logic [7:0]           unused_iter_idx;
  logic signed [{iw_m1}:0] unused_iter_x, unused_iter_y, unused_iter_z;

  cordic_accel #(
    .DataWidth ({dw}),
    .FracBits  ({fb}),
    .NumStages ({ns}),
    .Variant   ({variant}),
    .GuardInt  ({gi}),
    .GuardFrac ({gf}),
    .InDepth   ({ind}),
    .OutDepth  ({outd}),
    .AddrWidth (32),
    .IdWidth   (3),
    .UseRReady (0)
  ) i_accel (
    .clk_i, .rst_ni,
    .obi_req_i, .obi_gnt_o, .obi_addr_i, .obi_we_i, .obi_be_i, .obi_wdata_i,
    .obi_aid_i, .obi_rvalid_o, .obi_rready_i, .obi_rdata_o, .obi_rid_o,
    .obi_err_o, .irq_o,
    .str_in_valid_i, .str_in_ready_o, .str_in_func_i, .str_in_tag_i,
    .str_in_x_i, .str_in_y_i, .str_in_z_i,
    .str_out_valid_o, .str_out_ready_i, .str_out_x_o, .str_out_y_o,
    .str_out_z_o, .str_out_flags_o, .str_out_func_o, .str_out_tag_o,
    .dbg_stage_valid_o (unused_stage_valid),
    .dbg_iter_valid_o  (unused_iter_valid),
    .dbg_iter_idx_o    (unused_iter_idx),
    .dbg_iter_x_o      (unused_iter_x),
    .dbg_iter_y_o      (unused_iter_y),
    .dbg_iter_z_o      (unused_iter_z)
  );

endmodule
"""


def write_wrapper(cfg, path):
    dw = cfg["data_width"]
    iw = dw + cfg["guard_int"] + cfg["guard_frac"]
    path.write_text(WRAPPER_TEMPLATE.format(
        name=cfg["name"], top=cfg["top"], dw=dw, dw_m1=dw - 1,
        iw_m1=iw - 1, fb=cfg["frac_bits"], ns=cfg["num_stages"],
        variant=cfg["variant"], gi=cfg["guard_int"], gf=cfg["guard_frac"],
        ind=cfg["in_depth"], outd=cfg["out_depth"]))


INCLUDES = ["cordic_rom.svh", "cordic_regmap.svh", "cordic_defs.svh",
            "cordic_rom_fx.svh"]


def stage_rtl(work):
    """Copy the RTL next to the config.

    LibreLane refuses to read anything outside the config's own directory tree, so
    dir::../../../rtl is rejected outright. Staging a copy is simpler than arguing
    with it, and it also pins exactly which sources a run used.
    """
    dst = work / "rtl"
    dst.mkdir(parents=True, exist_ok=True)
    for f in SOURCES + INCLUDES:
        shutil.copy(RTL / f, dst / f)
    return dst


def config_for(cfg):
    """LibreLane config. Only keys the flow is known to accept, so an unknown-key
    error cannot waste a run."""
    files = [f"dir::rtl/{s}" for s in SOURCES]
    files.append(f"dir::{cfg['top']}.sv")
    return {
        "DESIGN_NAME": cfg["top"],
        "VERILOG_FILES": files,
        "VERILOG_INCLUDE_DIRS": ["dir::rtl"],
        "VERILOG_DEFINES": ["SYNTHESIS"],
        "CLOCK_PORT": "clk_i",
        "CLOCK_PERIOD": cfg["period_ns"],
        "PNR_SDC_FILE": "dir::cordic.sdc",
        "SIGNOFF_SDC_FILE": "dir::cordic.sdc",
        "FP_CORE_UTIL": cfg["util"],
        "PL_TARGET_DENSITY_PCT": cfg["util"] + 10,
        "PDK": "ihp-sg13g2",
        # Hold repair on a design with this many short register-to-register paths
        # needs more headroom than the default allows; the first attempt died on
        # [RSZ-0060] Max buffer count reached.
        "RSZ_HOLD_MAX_BUFFER_PCT": 75,
        "RSZ_HOLD_SLACK_MARGIN": 0.05,
    }


def latest_run(run_dir):
    runs = sorted(run_dir.glob("RUN_*"))
    return runs[-1] if runs else None


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--only", action="append", default=None)
    args = ap.parse_args(argv)

    if shutil.which("librelane") is None:
        print("librelane not on PATH", file=sys.stderr)
        return 1

    OUT.mkdir(parents=True, exist_ok=True)
    BUILD.mkdir(parents=True, exist_ok=True)

    configs = [dict(DEFAULTS, **c) for c in CONFIGS]
    if args.only:
        wanted = set(args.only)
        configs = [c for c in configs if c["name"] in wanted]
        if not configs:
            print(f"no configuration matched {sorted(wanted)}", file=sys.stderr)
            return 1

    summary = {}
    for cfg in configs:
        work = BUILD / cfg["name"]
        work.mkdir(parents=True, exist_ok=True)
        # Both live next to the config, since dir:: resolves relative to it.
        shutil.copy(PNR / "cordic.sdc", work / "cordic.sdc")
        stage_rtl(work)
        write_wrapper(cfg, work / f"{cfg['top']}.sv")
        cfg_path = work / "config.json"
        cfg_path.write_text(json.dumps(config_for(cfg), indent=1))

        print(f"[{cfg['name']}] place and route at {cfg['period_ns']} ns, "
              f"utilisation {cfg['util']}%", flush=True)
        log = BUILD / f"{cfg['name']}.log"
        with log.open("w") as fh:
            rc = subprocess.run(["librelane", "config.json"], cwd=work,
                                stdout=fh, stderr=subprocess.STDOUT).returncode
        text = log.read_text()
        if "fallback SDC" in text:
            print("  WARNING: LibreLane fell back to a generic SDC; timing from "
                  "this run is not trustworthy", file=sys.stderr)
        if rc != 0:
            print(f"  librelane failed, see {log}", file=sys.stderr)
            tail = "\n".join(text.splitlines()[-40:])
            print(tail, file=sys.stderr)
            return 1

        run = latest_run(work / "runs")
        if run is None:
            print(f"  no run directory under {work / 'runs'}", file=sys.stderr)
            return 1
        mpath = run / "final" / "metrics.json"
        if not mpath.exists():
            print(f"  {mpath} missing", file=sys.stderr)
            return 1
        metrics = json.loads(mpath.read_text())
        picked = {k: metrics.get(k) for k in METRICS}
        picked["run_dir"] = str(run.relative_to(ROOT))
        picked["config"] = cfg
        summary[cfg["name"]] = picked

        gds = next((run / "final" / "gds").glob("*.gds"), None)
        if gds:
            picked["gds"] = str(gds.relative_to(ROOT))
        for k in ("design__instance__count", "design__instance__area",
                  "design__die__area", "route__drc_errors",
                  "design__lvs_error__count"):
            print(f"    {k:<32} {picked.get(k)}", flush=True)

    path = OUT / "summary.json"
    if path.exists() and args.only:
        merged = json.loads(path.read_text())
        merged.update(summary)
        summary = merged
    path.write_text(json.dumps(summary, indent=1))
    print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
